
spring:
  datasource:
    url: jdbc:mysql://00.000.000.00:3306/mytest?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8099


#mybatis:
#  typeAliasesPackage: com.shark.entity
#  mapperLocations: classpath:mapper/*.xml
