
spring:
  datasource:
    url: jdbc:mysql://47.102.204.121:3306/mytest?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Zx!12300321
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8099


#mybatis:
#  typeAliasesPackage: com.shark.entity
#  mapperLocations: classpath:mapper/*.xml
